---
title: "R Notebook"
output: html_notebook
---



```{r}
library(nplr)
library(tidyverse)
```

```{r}
input_dir <- "./data/example-heatmap/"

```

```{r}

get_nplr_parameters <- function (file_path) {
  drug_data_orig <- read_csv(file_path)
  
  drug_data <-drug_data_orig
  colnames(drug_data) <- drug_data[1,]
  
  drug_data <- drug_data [-c(1,nrow(drug_data)-1, nrow(drug_data)),]
  
  drug_names <- colnames(drug_data)[2:(ncol(drug_data)-1)]
  
  all_drug_params <- NULL
  
  for (drug_name in drug_names) {
      model <- nplr(x = as.numeric(drug_data$Name), y = as.numeric(drug_data[[drug_name]])/100)
      nplr_params <- getPar(model)
      #nplr_params$params
      
      all_drug_params <- rbind(all_drug_params,  nplr_params$params)
  }
  
  all_drug_params_new <- t(all_drug_params) %>% 
                         as.data.frame() %>%
                         rownames_to_column("Row Labels") %>%
                         cbind (dox = "NA")
  
  colnames(all_drug_params_new) <- colnames(drug_data_orig)
  all_drug_params_new <- rbind (drug_data_orig, all_drug_params_new)
  all_drug_params_new[1,] <- as.list(paste0('"', all_drug_params_new[1,],'"'))
  all_drug_params_new
}


```


```{r}
inDir = "./data/example-heatmap/"
outDir = "./data/modified-data/"



for (file in list.files(inDir , pattern = ".csv")) {
  if (file == "main.csv") {next}
  newParams <- get_nplr_parameters(paste0(inDir, file))
  write.csv(newParams, paste0(outDir, file), quote=FALSE, row.names = FALSE,  na = "")
  #write.table(newParams, paste0(outDir, file), quote=FALSE, row.names = FALSE, col.names = TRUE, na = "", sep=",")
}


```

